const foodItems = [
    {
      id: 1,
      name: "Classic Burger",
      image: "https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      category: "Burger",
      price: 12.99,
      description: "A juicy beef patty with lettuce, tomato, and special sauce. Served with fries.",
      rating: 4.5,
      hotelName: "Burger Joint",
      ingredients: ["Beef Patty", "Lettuce", "Tomato", "Special Sauce", "Bun", "Fries"],
      prepTime: "15 minutes",
      calories: "600 kcal",
      reviews: [
        { user: "John Doe", comment: "Best burger ever!", stars: 5 },
        { user: "Jane Smith", comment: "Good but a bit pricey.", stars: 4 },
      ],
      tags: ["burger", "beef", "fast food"],
      discount: "10%",
      deliveryTime: "30-45 minutes"
    },
    {
      id: 2,
      name: "Margherita Pizza",
      image: "https://images.pexels.com/photos/1146760/pexels-photo-1146760.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      category: "Pizza",
      price: 15.50,
      description: "Fresh mozzarella, tomato sauce, and basil on a thin crust.",
      rating: 4.8,
      hotelName: "Pizza Palace",
      ingredients: ["Mozzarella", "Tomato Sauce", "Basil", "Dough"],
      prepTime: "20 minutes",
      calories: "800 kcal",
      reviews: [
        { user: "Alice Johnson", comment: "Delicious and authentic.", stars: 5 },
        { user: "Bob Williams", comment: "Could use more basil.", stars: 4 },
      ],
      tags: ["pizza", "italian", "vegetarian"],
      discount: null,
      deliveryTime: "25-35 minutes"
    },
    {
      id: 3,
      name: "Caesar Salad",
      image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      category: "Salad",
      price: 9.75,
      description: "Crisp romaine lettuce with parmesan and Caesar dressing. Add chicken for extra.",
      rating: 4.2,
      hotelName: "Salad Bar",
      ingredients: ["Romaine Lettuce", "Parmesan", "Caesar Dressing", "Croutons"],
      prepTime: "10 minutes",
      calories: "350 kcal",
      reviews: [
        { user: "Charlie Brown", comment: "Healthy and tasty.", stars: 4 },
        { user: "Diana Davis", comment: "Dressing was a bit too salty.", stars: 3 },
      ],
      tags: ["salad", "healthy", "vegetarian"],
      discount: null,
      deliveryTime: "20-30 minutes"
    },
    {
      id: 4,
      name: "Spaghetti Bolognese",
      image: "https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      category: "Pasta",
      price: 14.00,
      description: "Traditional Italian spaghetti with rich meat sauce and parmesan.",
      rating: 4.6,
      hotelName: "Italian Trattoria",
      ingredients: ["Spaghetti", "Meat Sauce", "Parmesan"],
      prepTime: "25 minutes",
      calories: "700 kcal",
      reviews: [
        { user: "Eve Fisher", comment: "Perfect comfort food.", stars: 5 },
        { user: "Frank Garcia", comment: "Good, but portion was small.", stars: 4 },
      ],
      tags: ["pasta", "italian", "meat"],
      discount: "15%",
      deliveryTime: "35-50 minutes"
    },
    {
      id: 5,
      name: "Chicken Tacos",
      image: "https://images.pexels.com/photos/1361197/pexels-photo-1361197.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      category: "Tacos",
      price: 11.25,
      description: "Soft tortillas filled with seasoned chicken, salsa, and toppings.",
      rating: 4.4,
      hotelName: "Taco Town",
      ingredients: ["Tortillas", "Chicken", "Salsa", "Toppings"],
      prepTime: "15 minutes",
      calories: "550 kcal",
      reviews: [
        { user: "Grace Hill", comment: "Great flavor!", stars: 4 },
        { user: "Henry Irwin", comment: "A bit spicy for me.", stars: 3 },
      ],
      tags: ["tacos", "mexican", "chicken"],
      discount: null,
      deliveryTime: "20-30 minutes"
    },
    {
      id: 6,
      name: "Vegetable Curry",
      image: "https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      category: "Curry",
      price: 13.50,
      description: "A flavorful mix of vegetables in a creamy curry sauce with rice.",
      rating: 4.7,
      hotelName: "Spice Garden",
      ingredients: ["Vegetables", "Curry Sauce", "Rice"],
      prepTime: "30 minutes",
      calories: "650 kcal",
      reviews: [
        { user: "Ivy Jones", comment: "Amazing curry!", stars: 5 },
        { user: "Jack King", comment: "Good, but could be spicier.", stars: 4 },
      ],
      tags: ["curry", "indian", "vegetarian"],
      discount: "20%",
      deliveryTime: "40-55 minutes"
    },
    {
      id: 7,
      name: "Chocolate Brownie",
      image: "https://images.pexels.com/photos/1126359/pexels-photo-1126359.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      category: "Dessert",
      price: 6.99,
      description: "Rich and fudgy chocolate brownie with vanilla ice cream and chocolate sauce.",
      rating: 4.9,
      hotelName: "Sweet Delights",
      ingredients: ["Chocolate", "Ice Cream", "Chocolate Sauce"],
      prepTime: "10 minutes",
      calories: "400 kcal",
      reviews: [
        { user: "Kelly Lane", comment: "Heavenly dessert!", stars: 5 },
        { user: "Leo Miller", comment: "Perfect for chocolate lovers.", stars: 5 },
      ],
      tags: ["dessert", "chocolate", "sweet"],
      discount: null,
      deliveryTime: "15-25 minutes"
    },
    {
      id: 8,
      name: "BBQ Ribs",
      image: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      category: "BBQ",
      price: 18.00,
      description: "Slow-cooked pork ribs with a tangy BBQ sauce. Served with coleslaw.",
      rating: 4.5,
      hotelName: "Smokin' Grill",
      ingredients: ["Pork Ribs", "BBQ Sauce", "Coleslaw"],
      prepTime: "45 minutes",
      calories: "900 kcal",
      reviews: [
        { user: "Mia Nelson", comment: "Fall-off-the-bone ribs!", stars: 5 },
        { user: "Noah Olson", comment: "Sauce was a bit too sweet.", stars: 4 },
      ],
      tags: ["bbq", "meat", "pork"],
      discount: null,
      deliveryTime: "50-65 minutes"
    },
    {
      id: 9,
      name: "Sushi Platter",
      image: "https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      category: "Sushi",
      price: 22.50,
      description: "Assorted sushi rolls and nigiri with fresh seafood and soy sauce.",
      rating: 4.8,
      hotelName: "Sushi Zen",
      ingredients: ["Salmon", "Tuna", "Rice", "Nori", "Soy Sauce"],
      prepTime: "30 minutes",
      calories: "750 kcal",
      reviews: [
        { user: "Olivia Parker", comment: "Fresh and delicious!", stars: 5 },
        { user: "Peter Quinn", comment: "Good variety.", stars: 4 },
      ],
      tags: ["sushi", "japanese", "seafood"],
      discount: null,
      deliveryTime: "35-50 minutes"
    },
    {
      id: 10,
      name: "Fruit Smoothie",
      image: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      category: "Drink",
      price: 7.25,
      description: "A refreshing blend of mixed fruits and yogurt.",
      rating: 4.3,
      hotelName: "Juice Bar",
      ingredients: ["Banana", "Strawberry", "Blueberry", "Yogurt"],
      prepTime: "5 minutes",
      calories: "250 kcal",
      reviews: [
        { user: "Rachel Roberts", comment: "Perfect for a hot day.", stars: 4 },
        { user: "Samuel Shaw", comment: "A bit too sweet.", stars: 3 },
      ],
      tags: ["smoothie", "fruit", "healthy"],
      discount: null,
      deliveryTime: "10-20 minutes"
    }
  ];
  
  export default foodItems;